SELECT USER_ID, Product_ID, SUM(QUANTITY_SOLD) AS TotalQuantity FROM SALES_PROJECT AS S GROUP BY USER_ID, Product_ID
HAVING 
SUM(QUANTITY_SOLD) = (SELECT MAX(TotalQuantity)FROM (SELECT SUM(QUANTITY_SOLD) AS TotalQuantity
 FROM Sales_PROJECT AS innerSales WHERE innerSales.USER_ID = S.USER_ID GROUP BY Product_ID) AS subquery);
 -- THE QUERY DISPLAYS THAT WHICH PRODUCT WAS POPULAR WITH RESPECT TO THE USER ON USER_ID AND THE TIMES OF PURCHASE OF A PRODUCT