SELECT
    p.Product_Name,
    SUM(s.QUANTITY_SOLD) AS TotalQuantitySold
FROM
    SALES_PROJECT AS s
JOIN
    PRODUCTS_PROJECT AS p ON s.Product_ID = p.Product_ID
GROUP BY
    p.Product_Name
ORDER BY
    TotalQuantitySold DESC
LIMIT 1;
-- THE MOST PURCHASED PRODUCT AMONG THE USERS WILL BE DISPLAYED WITH THE NUMBER OF TIMES THE PRODUCT WAS SOLD 