SELECT
    USER_ID,
    SUM(SALE_PRICE) AS TotalAmountSpent
FROM
    SALES_PROJECT
GROUP BY
    USER_ID;

-- THIS DISPLAYS THE TOTAL AMOUNT SPENT ON PRODUCTS WITH RESPECT TO THE USER_ID FROM THE TABLE OF SALES_PROJECT