SELECT
    s.USER_ID,
    COUNT(s.PRODUCT_ID) AS TotalOrders,
    SUM(s.SALE_PRICE) AS TotalAmountSpent
FROM
    SALES_PROJECT AS s
JOIN
    USERS_PROJECT AS u ON s.USER_ID = u.USER_ID
JOIN
    GOLD_USER_SIGNUP AS G ON u.USER_ID = G.USER_ID
WHERE
    s.CREATED_DATE < G.SIGNUP_DATE
GROUP BY
    s.USER_ID;
-- THIS WILL DISPLAY THE TOTAL ORDERS ASSOCIATED TO THE USER WITH RESPECT TO THEIR USER_ID AND THE TOTAL AMOUNT SPENT FOR THE ORDERS AND THE CREATED_DATE COLUMN FROM SALES_PROJECT DATA BE COMPARED WITH THE SIGNUP_DATE OF GOLD_USER_SIGNUP TABLE