SELECT
    SUM(Sale_PRICE) AS GoldUserRevenue
FROM
    GOLD_USER_SIGNUP AS S
JOIN
    Users_PROJECT AS U ON S.User_ID = U.User_ID
WHERE
    S.Membership = 'GOLD';

-- For this task, we will write a query containing the sale_price for the gold_user_signup table with which we will join the table of users_project using user_id in both the tables with the help of alias. The sum of the sale_price will be performed using sum(sale_price) and for which the alias will be given golduserrevenue, which will represent the revenue which is generated by the subscription holders only.