SELECT U.User_ID, COUNT(S.Product_ID) AS OrderCount FROM Users_PROJECT AS U 
JOIN GOLD_USER_SIGNUP AS G ON U.User_ID = G.User_ID
JOIN SALES_PROJECT AS S ON U.User_ID = S.User_ID
WHERE G.Membership = 'GOLD' GROUP BY U.User_ID;
-- THIS DISPLAYS THE GOLD MEMBERS HAVE ORDERED A SPECIFIC PRODUCT BASED ON THE PRODUCT_ID FROM USERS_PROJECT TABLE JOINED WITH GOLD_USER_SIGNUP
-- TABLE ALONG WITH THE JOINING OF SALES_PROJECT TABLE BASED ON USER_ID